export const defaultUsers = [
    {
      id: "1",
      name: "Emil Wagner",
      status: "Evening",
      username: "jodelkeller",
    },
    {
      id: "2",
      name: "Vincent Reichel",
      status: "Evening",
      username: "jodelkeller",
    },
    {
      id: "3",
      name: "Gretchen Casper",
      status: "Evening",
      username: "jodelkeller",
    },
    {
      id: "4",
      name: "Elizabeth Carroll",
      status: "Evening",
      username: "jodelkeller",
    },
    {
      id: "5",
      name: "Kayla Leuschke",
      status: "Evening",
      username: "jodelkeller",
    },
    {
      id: "6",
      name: "Johnny Hopie",
      status: "Evening",
      username: "jodelkeller",
    },
    {
      id: "7",
      name: "Sophia Davis",
      status: "Morning",
      username: "sophiadv",
    },
    {
      id: "8",
      name: "Oliver Twist",
      status: "Afternoon",
      username: "olivertwist",
    },
    {
      id: "9",
      name: "Liam Johnson",
      status: "Night",
      username: "liamjohn",
    },
    {
      id: "10",
      name: "Mia Miller",
      status: "Morning",
      username: "miam",
    },
    {
      id: "11",
      name: "Lucas Brown",
      status: "Afternoon",
      username: "lucasb",
    },
    {
      id: "12",
      name: "Amelia Smith",
      status: "Evening",
      username: "ameliasmith",
    },
    {
      id: "13",
      name: "Ethan Moore",
      status: "Night",
      username: "ethanmoore",
    },
    {
      id: "14",
      name: "Isabella White",
      status: "Morning",
      username: "isabellaw",
    },
    {
      id: "15",
      name: "Mason Thomas",
      status: "Afternoon",
      username: "masont",
    },
    {
      id: "16",
      name: "Ava Harris",
      status: "Evening",
      username: "avaharris",
    },
    {
      id: "17",
      name: "James Walker",
      status: "Morning",
      username: "jamesw",
    },
    {
      id: "18",
      name: "Harper Young",
      status: "Afternoon",
      username: "harpery",
    },
    {
      id: "19",
      name: "Elijah King",
      status: "Night",
      username: "elijahk",
    },
    {
      id: "20",
      name: "Charlotte Scott",
      status: "Evening",
      username: "charlottescott",
    },
  ];