name: Create Preview builds

on:
  push:
    branches:
      - stage

jobs:
  publish_preview_update:
    name: Build Android APK
    type: build
    params:
      platform: android
      profile: preview
