name: Create production builds

on:
  push:
    branches:
      - "archive-*"

jobs:
  build_android:
    name: Build Android
    type: build
    params:
      platform: android
      profile: production
