name: Publish to Test

on:
  push:
    branches:
      - dev

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install dependencies
        run: npm ci

      - name: Run semantic-release
        uses: cycjimmy/semantic-release-action@v4
        id: semantic
        with:
          dry_run: true
          semantic_version: 19
          extra_plugins: |
            @semantic-release/changelog@6
            @semantic-release/git@10
            @semantic-release/exec@6
            @semantic-release/commit-analyzer@9
            @semantic-release/release-notes-generator@10
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Get release version
        run: echo "NEW_VERSION=${{ steps.semantic.outputs.new_release_version }}" >> $GITHUB_ENV

      - name: Create Staging branch
        run: git checkout -b stage/${{ steps.semantic.outputs.new_release_version }}

      - name: Push Staging branch
        run: git push -u origin stage/${{ steps.semantic.outputs.new_release_version }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
