name: Publish to production

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Extract branch name
        run: echo "branch=${GITHUB_HEAD_REF:-${GITHUB_REF#refs/heads/}}" >> $GITHUB_OUTPUT
        id: get_branch

      - name: Check branch format and extract branch tag
        run: |
          BRANCH_NAME="${{ steps.get_branch.outputs.branch }}"
          if echo "$BRANCH_NAME" | grep -E -q '^stage-[0-9]+\.[0-9]+\.[0-9]+$'; then
            echo "Branch matches the required format."
            VERSION=$(echo "$BRANCH_NAME" | sed 's/stage-//')
            echo "VERSION=$VERSION" >> $GITHUB_ENV
          else
            echo "Branch does NOT match the required format."
            exit 1
          fi

      - name: Create Git tag
        run: |
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]"

          TAG_VERSION="${NEW_VERSION:-$VERSION}"

          git tag -a "v$TAG_VERSION" -m "Release version $TAG_VERSION"
          git push origin "v$TAG_VERSION"
        env:
          GITHUB_TOKEN: ${{ secrets.PERSONAL_TOKEN }}

      - name: Archive stage branch
        run: |
          git checkout -b archive-${{ steps.get_branch.outputs.branch }} ${{ steps.get_branch.outputs.branch }}
          git push origin archive-${{ steps.get_branch.outputs.branch }}
          git push -d origin ${{ steps.get_branch.outputs.branch }}
          git branch -D ${{ steps.get_branch.outputs.branch }}
        env:
          GITHUB_TOKEN: ${{ secrets.PERSONAL_TOKEN }}
